# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ddGng8k4okV+y22mzcM=,iv:9mBUUyFob0lZYoHTe19yJXfM6O8XbhU+Jo7CjKSXdKk=,tag:RY/wY604FYh2r9NQi/Q60w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:cbfQ8MBPY6KNrU9Uw0uN4VB3zC+ua5pTbZ+N9Vzb6VXmgvTG9g==,iv:00IBmIAFBAdHRVQXgQ9kGT+WLKPr+2kexLY1Lxw6LOY=,tag:8u6iM3yeQSe1p0VNktn8mg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:M4Qg5z/ZjvIYVd+p2w==,iv:/hUoBtMg3CHYk4HluYiQk/tI2mmcf/VMZaBEsFFsBv0=,tag:X/1NV4j9hG31nwo1WeRzUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ucnnx5euk9c7wp0lgmepaywjar7my70mu8k86pgvcznruhtk9gzsq5t8t0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOWtNYkoyeHZNTC8rdWtp
            SlpDbk9nYytQdEoxVWRVQUVTc3Fqd3hMN1NzClpHcWlRWXpZREh2bHUxTkJNcFJ3
            aEpDandya3pEU2ZubHB5eHh3SHZCUHMKLS0tIFM0NlNzOEhOL2thYWRvNHVXWENy
            TXN5bTVnMVB2eE13NGhwalMxaGUwTE0KSUG1Pr7Xuz9H5jSi6wAyZAn5kQpXLg1D
            anv17RNSoV70nVexDS4a0NoGo5onG6BroE9xTTbnYRFztMS9rZGBKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-20T23:40:20Z"
    mac: ENC[AES256_GCM,data:sTuQ5JMTNAEVxeGsC/6Sk9pFa607kaIZaaeC+pCxPqsJlHMC9BeBG2lcTb1Ea389ckVc6YaB0YYrjeqbhDoR3j3vl6DavmJ+BNwKn/w4ihU2H3uL9zCvqATKi2/L2+zKPOGfLf+A3st0kTZPt8U9sL/RqT3nEd9BtFCFIziLPvk=,iv:U6QkeB4zYXdu97Flp0oL3NAEjbvM9WcnLFpGQXEg8Lc=,tag:ltQDqtktKTjdC78lBKiqeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
